"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
import py2app
import sys
from os import getcwd
import os
from pathlib import Path

APP = ['Deepbeat.py']
DATA_FILES = [('resources/drumkits/Drum_Kit_1',
	['resources/drumkits/Drum_Kit_1/hihat.wav',
	'resources/drumkits/Drum_Kit_1/kick.wav',
	'resources/drumkits/Drum_Kit_1/snare.wav']),
('resources/drumkits/Drum_Kit_2',
	['resources/drumkits/Drum_Kit_2/hihat.wav',
	'resources/drumkits/Drum_Kit_2/kick.wav',
	'resources/drumkits/Drum_Kit_2/snare.wav']),
('resources/drumkits/Drum_Kit_3',
	['resources/drumkits/Drum_Kit_3/hihat.wav',
	'resources/drumkits/Drum_Kit_3/kick.wav',
	'resources/drumkits/Drum_Kit_3/snare.wav']),
('resources/drumkits/Drum_Kit_4',
	['resources/drumkits/Drum_Kit_4/hihat.wav',
	'resources/drumkits/Drum_Kit_4/kick.wav',
	'resources/drumkits/Drum_Kit_4/snare.wav']),
('resources',['resources/beatbox_model2.hdf5']),
('resources',['resources/beatbox.mid']),
('resources', ['resources/output.wav']),
('resources/images', ['resources/images/convert_to_midi5.png']),
('resources/images', ['resources/images/metronome_shadow.png']),
('resources/images', ['resources/images/metronome_unchecked.png']),
('resources/images', ['resources/images/midi_loop_shadow.png']),
('resources/images', ['resources/images/midi_loop_unchecked.png']),
('resources/images', ['resources/images/midi_pausebutton_shadow.png']),
('resources/images', ['resources/images/midi_playbutton_shadow.png']),
('resources/images', ['resources/images/pause_shadow.png']),
('resources/images', ['resources/images/playbutton_shadow.png']),
('resources/images', ['resources/images/recbutton_shadow.png']),
('resources/images', ['resources/images/scissors_shadow.png']),
('resources/images', ['resources/images/stopbutton_shadow.png'])]

PKGS = ['pygame','_sysconfigdata_m_darwin_darwin','tensorflow', 'keras', 'h5py', 'llvmlite','resampy', 'sklearn']
OPTIONS = {'argv_emulation': False,'iconfile':'resources/images/Deepbeat_Icon.icns',  'packages': PKGS}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)

#